application:
  name: zero2prod
  default_log_level: info
  host: 127.0.0.1
  port: 8080
database:
  protocol: postgres
  username: postgres
  password: password
  port: 5432
  host: localhost
  database_name: newsletter