application:
  host: 127.0.0.1
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  database_name: newsletter
  require_ssl: false
email_client:
  api_base_url: http://127.0.0.1:1080
  sender_email: 9YfJ5@example.com
  auth_header: X-Postmark-Server-Token
  auth_token: secret_token