application:
  host: 127.0.0.1
  base_url: http://127.0.0.1
  hmac_secret: super-long-secret-string-for-testing
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  database_name: newsletter
  require_ssl: false
email_client:
  api_base_url: localhost
  sender_email: 9YfJ5@example.com
  auth_header: X-Mail-Server-Token
  auth_token: secret_token