application:
  host: 127.0.0.1
  base_url: http://127.0.0.1
  hmac_secret: j3oO2gtFn8ep8AAGHXDHSmCeYsyvX1Lz8hxDs8csSJ6w5qynXC8P6Xe4eSi0Pc+fyRpAYUcSkZJ7ajjhp6uz5Q==
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  database_name: newsletter
  require_ssl: false
email_client:
  api_base_url: localhost
  sender_email: 9YfJ5@example.com
  auth_header: X-Mail-Server-Token
  auth_token: secret_token