application:
  host: 127.0.0.1
  base_url: http://127.0.0.1
  # base64 required 64 bytes long crypt string
  flash_msg_key: j3oO2gtFn8ep8AAGHXDHSmCeYsyvX1Lz8hxDs8csSJ6w5qynXC8P6Xe4eSi0Pc+fyRpAYUcSkZJ7ajjhp6uz5Q==
  redis_url: redis://127.0.0.1:6379
  redis_session_key: j3oO2gtFn8ep8AAGHXDHSmCeYsyvX1Lz8hxDs8csSJ6w5qynXC8P6Xe4eSi0Pc+fyRpAYUcSkZJ7ajjhp6uz5Q==
  idempotency_expiration_millis: 50
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  database_name: newsletter
  require_ssl: false
email_client:
  username: 9YfJ5@example.com
  password: password
  host: localhost
  port: 1025
  sender_email: 9YfJ5@example.com
  require_tls: false
  request_timeout_millis: 50